# Param Shah
## 240905320
## CSE-D 33
### Lab 1: NumPy

In [6]:
import numpy as np
import matplotlib as mp
import pandas as pd

In [7]:
import sys
np.set_printoptions(threshold=sys.maxsize)

Q1. Convert a 1-D array into a 2-D array with 3 rows. 

In [8]:
x = np.array([0,1,2,3,4,5,6,7,8])

print("Original Array")
print(x)
print("\n")

x = x.reshape(3,3)

print("Modified Array")
print(x)
print("\n")

Original Array
[0 1 2 3 4 5 6 7 8]


Modified Array
[[0 1 2]
 [3 4 5]
 [6 7 8]]




Q2. Replace all odd numbers in the given array with -1 

In [9]:
x = np.array([0,1,2,3,4,5,6,7,8,9])

print("Original Array")
print(x)
print("\n")

for i in range(len(x)):
    if x[i] % 2 != 0:
        x[i] = -1

print("Modified Array")
print(x)
print("\n")


Original Array
[0 1 2 3 4 5 6 7 8 9]


Modified Array
[ 0 -1  2 -1  4 -1  6 -1  8 -1]




Q3. Find the positions of elements in x where its value is more than its corresponding element in y, and elements in x where its value is 
equals to its corresponding element in y.

In [10]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89])
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

greater = np.where(x > y)

equal = np.where(x == y)

print(greater)
print(equal)

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


Q4. Extract the first four columns of this 2-D array. 

In [11]:
x = np.arange(100).reshape(5,-1)

print("Original Array")
print(x)
print("\n")

y = x[:,0:4]

print("Modified Array")
print(y)
print("\n")


Original Array
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]]


Modified Array
[[ 0  1  2  3]
 [20 21 22 23]
 [40 41 42 43]
 [60 61 62 63]
 [80 81 82 83]]




Q5. Generate a 1-D array of 10 random integers. Each integer should be a number between 30 and 40 (inclusive).

In [12]:
x = np.random.randint(30, 41, 10)

print(x)

[33 40 40 37 33 36 32 32 40 31]


Q2. Consider the following matrices : 
A= ((1, 2, 3), (4, 5, 6), (7, 8, 10)) and   B = ((7, 8, 10) ,(4, 5, 6), (1, 2, 3)) 

Write a python program to perform the following using Numeric Python (numpy). \
i) Add and Subtract of the Matrix A and B, print the resultant matrix C for add and E for subtract. \
ii) Compute the sum of all elements of Matrix A, sum of each column of Matrix B and sum of each row of Matrix C \
iii) Product of two matrices A and B, and print the resultant matrix D \
iv) Sort the elements of resultant matrix C and print the resultant Matrix E.                    
v) Transpose the Matrix E and print the result 

In [16]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 10]])

B = np.array([[7, 8, 10],
              [4, 5, 6],
              [1, 2, 3]])

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

C = A + B
E = A - B

print("\nMatrix C (A + B):")
print(C)

print("\nMatrix E (A - B):")
print(E)

print("\nSum of all elements of Matrix A:")
print(np.sum(A))

print("\nSum of each column of Matrix B:")
print(np.sum(B, axis=0))

print("\nSum of each row of Matrix C:")
print(np.sum(C, axis=1))

D = np.dot(A, B)

print("\nMatrix D (A x B):")
print(D)

E = np.sort(C)

print("\nMatrix E after sorting each row:")
print(E)

tempE = C.reshape(-1)

print("\nFlattened Matrix C:")
print(tempE)

tempE = np.sort(tempE)

print("\nFlattened Matrix C after sorting:")
print(tempE)

tempE = tempE.reshape(3, 3)

print("\nMatrix E after sorting all elements:")
print(tempE)

T = tempE.T

print("\nTranspose of Matrix E:")
print(T)

Matrix A:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8 10]]

Matrix B:
[[ 7  8 10]
 [ 4  5  6]
 [ 1  2  3]]

Matrix C (A + B):
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

Matrix E (A - B):
[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]

Sum of all elements of Matrix A:
46

Sum of each column of Matrix B:
[12 15 19]

Sum of each row of Matrix C:
[31 30 31]

Matrix D (A x B):
[[ 18  24  31]
 [ 54  69  88]
 [ 91 116 148]]

Matrix E after sorting each row:
[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

Flattened Matrix C:
[ 8 10 13  8 10 12  8 10 13]

Flattened Matrix C after sorting:
[ 8  8  8 10 10 10 12 13 13]

Matrix E after sorting all elements:
[[ 8  8  8]
 [10 10 10]
 [12 13 13]]

Transpose of Matrix E:
[[ 8 10 12]
 [ 8 10 13]
 [ 8 10 13]]
